---
# Load boxes presets

- block:
    - name: Search box presets
      find:
        paths: "{{ role_path }}/defaults/boxes"
        patterns: "*.yml"
      register: vagrant_presets_search_boxes_result
      delegate_to: localhost

    - name: Load box presets
      include_vars:
        file: "{{ file.path }}"
        name: vagrant_presets_box
      loop: "{{ vagrant_presets_search_boxes_result.files }}"
      loop_control:
        label: "{{ file.path | basename }}"
        loop_var: file
      register: vagrant_presets_load_boxes_result
      delegate_to: localhost

    - name: Setup fact with boxes presets
      set_fact:
        vagrant_presets_boxes: >-
          {{ vagrant_presets_load_boxes_result.results
             | map(attribute="ansible_facts.vagrant_presets_box")
             | list
             | to_json
             | from_json
             | json_query(vagrant_presets_boxes_json_query)
             | to_nice_yaml
             | regex_replace('playbook: (.*)',
                             'playbook: "'
                             + vagrant_presets_playbooks_path
                             + "/"
                             + "\1"
                             + '"')
             | from_yaml }}

    - name: Setup directory for playbooks
      file:
        path: "{{ vagrant_presets_playbooks_path }}"
        state: directory
        mode: 0700

    - name: Setup playbooks
      copy:
        src: "files/{{ item.playbook | basename }}"
        dest: "{{ item.playbook }}"
        mode: 0600
      loop: "{{ vagrant_presets_boxes }}"
      loop_control:
        label: "{{ item.playbook }}"
  tags:
    - role::vagrant_presets
    - role::vagrant_presets::boxes
