---
# Role tasks

- name:
  set_fact:
    vagrant_presets_files: "{{ role_path }}/files"
  tags:
    - role::vagrant_presets

- name: configure boxes presets
  include_tasks: boxes.yml
  tags:
    - role::vagrant_presets
    - role::vagrant_presets::boxes

- name: configure vms presets
  include_tasks: vms.yml
  tags:
    - role::vagrant_presets
    - role::vagrant_presets::vms
