---
# Role tasks

- name: Configure boxes presets
  include_tasks: boxes.yml
  tags:
    - role::vagrant_presets
    - role::vagrant_presets::boxes

- name: Configure vms presets
  include_tasks: vms.yml
  tags:
    - role::vagrant_presets
    - role::vagrant_presets::vms
